### ISSUE TITLE
Add support for order property on flex items

### ISSUE THREAD

**Issue by okaune** [ludens-reklamebyra/react-crisscross#22]
Flex allows to change the order of elements via the `order` property. The question is how it should be implemented. The order property is most useful for changing the layout on different breakpoints. It is therefore closely linked to the media queries. The question is if we want to change the media query objects from just setting the flex-basis, to also allow other properties. Eg:
```jsx
const xsSettings = {
  basis: 3,
  order: -1,
  ...
}
const mdSettings = {
  basis: 3,
  ...
}

<Layout container>
  <Layout item xs={smSettings} md={mdSettings}>
    {/* Content */}
  </Layout>
</Layout>
```

**Comment by okaune** [comment]
What do you think @oyvindhermansen ?

**Comment by oyvindhermansen** [comment]
I agree that this could be a solution to the order property, but my main concern is that there will be 1000 objects containing basis and order for every `Layout item` in an application. If I had a complex layout than possibly had 10 layout items, and every one of them had one object pr media query, I would have gone insane! haha. Is there any other way we could do this? Because i think we should include order somehow. I'm not just convinced that this is the way to go. If the arguments are good enough for this solution I'm willing to do it tho. What do you think?

**Comment by okaune** [comment]
Thinking more like converting so everything can be assingned to the media queries. Like this:
```jsx
<Layout container sm={{wrap: 'wrap'}}>
  <Layout item xs={{basis: 3, alignSelf: 'flex-start'}} md={{basis: 6}}>
    {/* Content */}
  </Layout>
</Layout>
```

**Comment by okaune** [comment]
What do you think @oyvindhermansen ?
